# Generated by Django 3.2.6 on 2022-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to=''),
        ),
    ]
