# Generated by Django 3.2.6 on 2022-04-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0007_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Childrenhelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('document_image', models.ImageField(blank=True, default='user.jpg', null=True, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
