# Generated by Django 3.2.6 on 2022-04-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0008_childrenhelp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childrenhelp',
            name='date',
        ),
    ]
