# Generated by Django 3.2.6 on 2022-04-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0009_remove_childrenhelp_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Childrenhelp',
        ),
    ]
