# Generated by Django 3.2.6 on 2022-04-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0011_childrenhelp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Childrenhelp',
        ),
    ]
