# Generated by Django 3.2.6 on 2022-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0015_childrenhelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenhelp',
            name='account_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
