# Generated by Django 3.2.6 on 2022-04-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0016_alter_childrenhelp_account_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Childrenhelp',
        ),
    ]
