# Generated by Django 3.2.6 on 2022-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0017_delete_childrenhelp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=12)),
                ('desc', models.TextField()),
            ],
        ),
    ]
