# Generated by Django 3.2.6 on 2022-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0018_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='account',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
