# Generated by Django 3.2.6 on 2022-04-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0019_help_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daycare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('service_time', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
    ]
