# Generated by Django 3.2.6 on 2022-04-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0020_daycare'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
