# Generated by Django 3.2.6 on 2022-05-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0022_district_school_schooldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='childname',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
