# Generated by Django 3.2.6 on 2022-05-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0023_schooldetails_childname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
