# Generated by Django 3.2.6 on 2022-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0025_alter_daycare_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycare',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
