# Generated by Django 3.2.6 on 2022-05-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0026_alter_daycare_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Child.customer'),
        ),
    ]
