# Generated by Django 3.2.6 on 2022-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0030_auto_20220506_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('option', models.CharField(choices=[('Donation', 'Donation'), ('Product Cost', 'Product Cost')], max_length=200)),
                ('product_name_and_quentity', models.CharField(blank=True, max_length=100, null=True)),
                ('bkashNumber', models.CharField(max_length=20)),
                ('Transaction_ID', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
