# Generated by Django 3.2.6 on 2022-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0032_nagadpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'paid')], max_length=200, null=True),
        ),
    ]
